# -*- coding: utf-8 -*-
"""haberçekme

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IMVnTQRVWLsdjxAPM7Q_6dmZYYKBhx7L
"""

import requests
from bs4 import BeautifulSoup

def haberleri_cek(haber_sitesi_url):
    cevap = requests.get(haber_sitesi_url)
    soup = BeautifulSoup(cevap.content, 'html.parser')

    haber_listesi = []

    haber_basliklari = soup.find_all('h2', class_='haber-baslik')

    for baslik in haber_basliklari:
        haber_listesi.append(baslik.text.strip())

    return haber_listesi

def haberleri_dosyaya_kaydet(haber_listesi, dosya_adı):
    with open(dosya_adı, 'w', encoding='utf-8') as dosya:
        for haber in haber_listesi:
            dosya.write(f"{haber}\n")

if __name__ == "__main__":
    haber_sitesi_url = 'haber sitesi url'
    dosya_adı = 'haberler.txt'

    haber_listesi = haberleri_cek(haber_sitesi_url)

    if haber_listesi:
        haberleri_dosyaya_kaydet(haber_listesi, dosya_adı)
        print(f"Haberler başarıyla '{dosya_adı}' dosyasına kaydedildi.")
    else:
        print("Haberler çekilemedi.")